<a href="https://colab.research.google.com/github/MateoProjects/IA/blob/main/Pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Guide

## Tensors

In [1]:
import torch
import numpy as np

**Definició de tensors**

In [2]:
a = torch.tensor([1, 2])
b = torch.tensor([8, 9])
c = a + b
print(c)


tensor([ 9, 11])


* Puc convertir-los a numpy i a l'inversa

In [3]:
a = torch.tensor([1, 2])
print(a.numpy())

a = np.array([1, 2])
torch.from_numpy(a)


[1 2]


tensor([1, 2])

* Tensors de tipus float

In [4]:
torch.FloatTensor([[1, 2], [2, 1]])

tensor([[1., 2.],
        [2., 1.]])

* Definicio del tipus del tensor

In [5]:
torch.tensor([[1, 2], [2, 1]], dtype=torch.bool)


tensor([[True, True],
        [True, True]])

* Com en numpy puc definir o tensors amb valors rand o només d'uns

In [6]:
# tensor de 2D amb 2 elements per D
print(torch.ones(3, 2))
print(torch.rand(3, 2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0.7139, 0.9844],
        [0.5556, 0.4576],
        [0.4606, 0.3923]])


### Operacions

* Amb **.sum** puc sumar tots els elements del tensor. 

In [7]:
a = torch.tensor([[2,3], [1,2]])
a.sum()

tensor(8)

* O la transposada

In [8]:
a.t()

tensor([[2, 1],
        [3, 2]])

* El size

In [9]:
a.size()

torch.Size([2, 2])

* Puc crear un tensor i sumnar-lo sobre un ja existent.

In [10]:
b = torch.tensor([[4,2],[3,2]])
a.add(b)

tensor([[6, 5],
        [4, 4]])

## CPU o GPU

In [11]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

Per moure un tensor cap al device

In [12]:
x = torch.tensor([[2, 3], [1, 2]])
x.to(device)


tensor([[2, 3],
        [1, 2]], device='cuda:0')