<a href="https://colab.research.google.com/github/MateoProjects/DeepLearning/blob/master/Deep_Learning_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introducció Python Deep Learning**

Per comprovar la versió de tensor flow disponible utilitzarem la següent comanda

In [ ]:
%tensorflow_version 2.x

##Imports 

In [ ]:
import tensorflow as tf
from tensorflow import keras
print("GPU available: ", tf.test.is_gpu_available())
print(tf.keras.__version__)

GPU available:  True
2.3.0-tf


##Recordatori coses bàsiques de Python

1. Declaració de iteradors



In [ ]:
vec = [1 , 2 ,3 ]
it = iter(vec)
print(next(it))
print("Type of it is: " , type(it))


1
Type of it is:  <class 'list_iterator'>


2. Decoradors

*   Augmenten les funcionalitats d'una funció sense modificarla




In [ ]:
def voy_a_imprimir_hola():
  print("Hola")

def my_decorator(func):
  def wrapper():
    print("[Aviso que voy a decir algo]")
    func()
    print("[Aviso que ya he dicho algo]")
  return wrapper

voy_a_imprimir_hola = my_decorator(voy_a_imprimir_hola)
voy_a_imprimir_hola()

[Aviso que voy a decir algo]
Hola
[Aviso que ya he dicho algo]



* Un altre forma i més fàcil és posar **@my_decorator** sobre la funcio a decorar i el codi ja ho entendrà completament sol 

In [ ]:
@my_decorator
def voy_a_imprimir_hola():
  print("Hola")

def my_decorator(func):
  def wrapper():
    print("[Aviso que voy a decir algo]")
    func()
    print("[Aviso que ya he dicho algo]")
  return wrapper

voy_a_imprimir_hola()

[Aviso que voy a decir algo]
Hola
[Aviso que ya he dicho algo]


#Tensor

* Estructura bàsica de dades a la que es fa referència quan parlem d'arrays multidimensionals en NumPy 

1.   Rank : número d'eixos. A un tensor que conte sols conté un sol número s'anomenarà escalar o tensor 0D . Un array de números sel anomenarà vector o tensor 1D . Un array de arrays ( Matriu) o tensor 2D . Si posem aquesta matriu dins d'un altre array obtindrem tensor 3D i així succesivament. En Numpy això és el ndim
2.   Forma: Tupla d'enteres que descriuen quantes dimensions té el tensor en cada eix.  Dins de numpy aquest atribut sel anomena **shape** . Per exemple el vector tindrà un únic element , mentres que un escalar tindrà un shape buit.
3. Tipus de dades : Aquest atribut indicar el tipus de dades que conté el tensor. A numpy s'anomena dtype a aquest atribut. 




In [ ]:
import numpy as np

x = np.array(8.2) # declaro array de numpy de 8 elements
print("x : " , x)
print("x dimension is: " , x.ndim) #indica les dimensions del array
print("x number of shapes : " , x.shape) # indica el número de dimensions del array
print("x size: " , x.size) # tamany de l'array
print("x type : " , x.dtype)

x :  8.2
x dimension is:  0
x number of shapes :  ()
x size:  1
x type :  float64


Ara es passa a fer la prova amb un tensor 1D

In [ ]:
import numpy as np

x = np.array([5,3,5,6]) # declaro array de numpy de 8 elements
print("x : " , x)
print("x dimension is : " , x.ndim) #indica les dimensions del array
print("x number of shapes : " , x.shape) # indica el número de dimensions del array
print("x size : " , x.size) # tamany de l'array
print("x type : " , x.dtype)

x :  [5 3 5 6]
x dimension is :  1
x number of shapes :  (4,)
x size :  4
x type :  int64


Tensor 2D

In [ ]:
import numpy as np

x = np.array([[5,3,5,6],[5,3,5,6]]) # declaro array de numpy de 8 elements
print("x : " , x)
print("x dimension is : " , x.ndim) #indica les dimensions del array
print("x number of shapes : " , x.shape) # indica el número de dimensions del array
print("x size : " , x.size) # tamany de l'array
print("x type : " , x.dtype)

x :  [[5 3 5 6]
 [5 3 5 6]]
x dimension is :  2
x number of shapes :  (2, 4)
x size :  8
x type :  int64


Tensor 3D

In [ ]:
import numpy as np

x = np.array([[[5,3],[5,6]],[[5,6] , [7,8]]]) # declaro array de numpy de 8 elements
print("x : " , x)
print("x dimension is : " , x.ndim) #indica les dimensions del array
print("x number of shapes : " , x.shape) # indica el número de dimensions del array
print("x size : " , x.size) # tamany de l'array
print("x type : " , x.dtype)

x :  [[[5 3]
  [5 6]]

 [[5 6]
  [7 8]]]
x dimension is :  3
x number of shapes :  (2, 2, 2)
x size :  8
x type :  int64


##Funcions útils NumPy

In [ ]:
print("--- Matriu de 0 ---")
print(np.zeros((3,3)))
print("--- Matriu de 1 ---")
print(np.ones((3,3)))
print("--- Matriu d'identitat ---")
print(np.eye((3)))
print("--- Matriu random ---")
print(np.random.random((3,3)))

--- Matriu de 0 ---
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--- Matriu de 1 ---
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--- Matriu d'identitat ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--- Matriu random ---
[[0.28967359 0.13499649 0.0327376 ]
 [0.30643659 0.03706831 0.21663384]
 [0.27352262 0.37199342 0.83111337]]


Quan vui afectuar una múltiplicació de matrius però aquestes tenen diferents files i columnes puc fer el següent:

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8] ,  [1,2] , [3,4]])
print(a)
print(b)
c = a.dot(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[7 8]
 [1 2]
 [3 4]]
[[18 24]
 [51 66]]


Quan vulgui canviar la forma dels tensors haure de fer el següent

In [ ]:
x = np.array([[1,2,3,4,5,6]])
print(x)
print("x shape : " , x.shape)
y = np.reshape(x , (2,3))
print(y)
print("y shape : " , y.shape)
z = np.reshape(x , (2 , -1))
print(z)
print("z shape : " , z.shape)

[[1 2 3 4 5 6]]
x shape :  (1, 6)
[[1 2 3]
 [4 5 6]]
y shape :  (2, 3)
[[1 2 3]
 [4 5 6]]
z shape :  (2, 3)


Per afegir una dimensio a un array :

In [ ]:
x = np.array([[1,2,3],[5,4,3]])
print("x shape is : " , x.shape)
y = np.expand_dims(x , 1)
print(" y :\n" , y)
print("y shape :" , y.shape)


x shape is :  (2, 3)
 y :
 [[[1 2 3]]

 [[5 4 3]]]
y shape : (2, 1, 3)


Per esborrar una dimensió :

In [ ]:
x = np.array([[[1,2,3]],[[5,4,3]]])
print("x shape is : " , x.shape)
y = np.squeeze(x , 1)
print(" y :\n" , y)
print("y shape :" , y.shape)

x shape is :  (2, 1, 3)
 y :
 [[1 2 3]
 [5 4 3]]
y shape : (2, 3)


Per saber el valor màxim d'un tensor es fa servir:


* np.argmax(x) per obtenir la posició del valor màxim dins la x
* np.max(x) per saber el valor màxim dins la x



In [ ]:
print(x)
print(np.argmax(x))
print(np.max(x))

[[[1 2 3]]

 [[5 4 3]]]
3
5


Puc especificar sobre quin eix es pot fer la cerca

In [ ]:
print("Eix 0 el màx es troba a : ",np.argmax(x, axis=0))
print("Eix 0 el màx es troba a : ",np.argmax(x ,axis=1))

Eix 0 el màx es troba a :  [[1 1 0]]
Eix 0 el màx es troba a :  [[0 0 0]
 [0 0 0]]
